onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /CHKN_Single/clk
add wave -noupdate /CHKN_Single/reset
add wave -noupdate /CHKN_Single/validIn
add wave -noupdate /CHKN_Single/iLayer
add wave -noupdate /CHKN_Single/ValidOut
add wave -noupdate /CHKN_Single/llrNew
add wave -noupdate -radix binary /CHKN_Single/activeCols
add wave -noupdate -radix decimal -childformat {{{/CHKN_Single/llr_new[0]} -radix decimal} {{/CHKN_Single/llr_new[1]} -radix decimal} {{/CHKN_Single/llr_new[2]} -radix decimal} {{/CHKN_Single/llr_new[3]} -radix decimal} {{/CHKN_Single/llr_new[4]} -radix decimal} {{/CHKN_Single/llr_new[5]} -radix decimal} {{/CHKN_Single/llr_new[6]} -radix decimal} {{/CHKN_Single/llr_new[7]} -radix decimal} {{/CHKN_Single/llr_new[8]} -radix decimal} {{/CHKN_Single/llr_new[9]} -radix decimal} {{/CHKN_Single/llr_new[10]} -radix decimal} {{/CHKN_Single/llr_new[11]} -radix decimal} {{/CHKN_Single/llr_new[12]} -radix decimal} {{/CHKN_Single/llr_new[13]} -radix decimal} {{/CHKN_Single/llr_new[14]} -radix decimal} {{/CHKN_Single/llr_new[15]} -radix decimal}} -subitemconfig {{/CHKN_Single/llr_new[0]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[1]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[2]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[3]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[4]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[5]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[6]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[7]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[8]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[9]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[10]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[11]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[12]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[13]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[14]} {-height 15 -radix decimal} {/CHKN_Single/llr_new[15]} {-height 15 -radix decimal}} /CHKN_Single/llr_new
add wave -noupdate -radix decimal -childformat {{{/CHKN_Single/eta_sum_in[0]} -radix decimal} {{/CHKN_Single/eta_sum_in[1]} -radix decimal} {{/CHKN_Single/eta_sum_in[2]} -radix decimal} {{/CHKN_Single/eta_sum_in[3]} -radix decimal} {{/CHKN_Single/eta_sum_in[4]} -radix decimal} {{/CHKN_Single/eta_sum_in[5]} -radix decimal} {{/CHKN_Single/eta_sum_in[6]} -radix decimal} {{/CHKN_Single/eta_sum_in[7]} -radix decimal} {{/CHKN_Single/eta_sum_in[8]} -radix decimal} {{/CHKN_Single/eta_sum_in[9]} -radix decimal} {{/CHKN_Single/eta_sum_in[10]} -radix decimal} {{/CHKN_Single/eta_sum_in[11]} -radix decimal} {{/CHKN_Single/eta_sum_in[12]} -radix decimal} {{/CHKN_Single/eta_sum_in[13]} -radix decimal} {{/CHKN_Single/eta_sum_in[14]} -radix decimal} {{/CHKN_Single/eta_sum_in[15]} -radix decimal}} -subitemconfig {{/CHKN_Single/eta_sum_in[0]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[1]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[2]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[3]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[4]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[5]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[6]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[7]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[8]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[9]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[10]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[11]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[12]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[13]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[14]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_in[15]} {-height 15 -radix decimal}} /CHKN_Single/eta_sum_in
add wave -noupdate -radix decimal -childformat {{{/CHKN_Single/eta_sum_out[0]} -radix decimal} {{/CHKN_Single/eta_sum_out[1]} -radix decimal} {{/CHKN_Single/eta_sum_out[2]} -radix decimal} {{/CHKN_Single/eta_sum_out[3]} -radix decimal} {{/CHKN_Single/eta_sum_out[4]} -radix decimal} {{/CHKN_Single/eta_sum_out[5]} -radix decimal} {{/CHKN_Single/eta_sum_out[6]} -radix decimal} {{/CHKN_Single/eta_sum_out[7]} -radix decimal} {{/CHKN_Single/eta_sum_out[8]} -radix decimal} {{/CHKN_Single/eta_sum_out[9]} -radix decimal} {{/CHKN_Single/eta_sum_out[10]} -radix decimal} {{/CHKN_Single/eta_sum_out[11]} -radix decimal} {{/CHKN_Single/eta_sum_out[12]} -radix decimal} {{/CHKN_Single/eta_sum_out[13]} -radix decimal} {{/CHKN_Single/eta_sum_out[14]} -radix decimal} {{/CHKN_Single/eta_sum_out[15]} -radix decimal}} -subitemconfig {{/CHKN_Single/eta_sum_out[0]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[1]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[2]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[3]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[4]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[5]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[6]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[7]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[8]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[9]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[10]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[11]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[12]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[13]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[14]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_out[15]} {-height 15 -radix decimal}} /CHKN_Single/eta_sum_out
add wave -noupdate -childformat {{{/CHKN_Single/eta_sum_read[0]} -radix decimal} {{/CHKN_Single/eta_sum_read[1]} -radix decimal} {{/CHKN_Single/eta_sum_read[2]} -radix decimal} {{/CHKN_Single/eta_sum_read[3]} -radix decimal} {{/CHKN_Single/eta_sum_read[4]} -radix decimal} {{/CHKN_Single/eta_sum_read[5]} -radix decimal} {{/CHKN_Single/eta_sum_read[6]} -radix decimal} {{/CHKN_Single/eta_sum_read[7]} -radix decimal} {{/CHKN_Single/eta_sum_read[8]} -radix decimal} {{/CHKN_Single/eta_sum_read[9]} -radix decimal} {{/CHKN_Single/eta_sum_read[10]} -radix decimal} {{/CHKN_Single/eta_sum_read[11]} -radix decimal} {{/CHKN_Single/eta_sum_read[12]} -radix decimal} {{/CHKN_Single/eta_sum_read[13]} -radix decimal} {{/CHKN_Single/eta_sum_read[14]} -radix decimal} {{/CHKN_Single/eta_sum_read[15]} -radix decimal}} -subitemconfig {{/CHKN_Single/eta_sum_read[0]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[1]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[2]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[3]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[4]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[5]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[6]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[7]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[8]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[9]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[10]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[11]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[12]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[13]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[14]} {-height 15 -radix decimal} {/CHKN_Single/eta_sum_read[15]} {-height 15 -radix decimal}} /CHKN_Single/eta_sum_read
add wave -noupdate /CHKN_Single/currIter
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {279 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {211 ps} {490 ps}
